exper_name: "Stellarator_VMEC_3_Obj_Optimization"
description: "Optimizing a 3D stellarator plasma boundary using VMEC++ to find optimal Pareto solutions for volume, aspect ratio, and magnetic shear."
save_dir: "./moo_results/"
save_suffix: "stellarator_vmec_3_obj"

resume: False

model:
  name: zgca,gemini-2.5-flash-nothinking 
  base_url: http://35.220.164.252:3888/v1/chat/completions
  api_key: sk-UQSdTgxybYPRjg0WBq3v6NCxMMDNuIanMCdHy6mp9cGWPCTs
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.7
  mutation_prob: 0.3
  explore_prob: 0
use_au: False


goals: [volume, aspect_ratio, magnetic_shear]
optimization_direction: [max, min, max]


prompt_info_path: ./problem/stellarator_vmec/vmec.yaml
evalutor_path: problem.stellarator_vmec.evaluator


vmec:

  project_path: "/home/wenhao/project/MOLLM-main/problem/stellarator_vmec/vmecpp/examples/data" 

  input_file: "input.w7x" 

  output_file: "wout_w7x.nc" 

optimization:
  pop_size: 40
  eval_budget: 5000
  log_freq: 50