name: mollm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - about-time=4.2.1
  - alive-progress=3.2.0
  - ampl-asl=1.0.0
  - asttokens=3.0.0
  - autograd=1.8.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cloudpickle=3.1.1
  - cma=3.2.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - deprecated=1.2.18
  - dill=0.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fonttools=4.60.1
  - freetype=2.14.1
  - grapheme=0.6.0
  - icu=73.1
  - importlib-metadata=8.7.0
  - ipopt=3.14.19
  - ipykernel=7.0.1
  - ipyparallel=9.0.2
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libjpeg-turbo=3.1.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libscotch=7.0.4
  - libsodium=1.0.20
  - libspral=2025.05.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lmdb=0.9.31
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - metis=5.1.0
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nlopt=2.10.0
  - numpy=2.3.4
  - openjpeg=2.5.3
  - openssl=3.5.4
  - packaging=25.0
  - pagmo=2.19.1
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=11
  - pygments=2.19.2
  - pygmo=2.19.7
  - pymoo=0.6.1.5
  - pyparsing=3.2.5
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.3
  - scipy=1.16.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2022.2.0
  - tk=8.6.15
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - unicodedata2=16.0.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - wrapt=1.17.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.10.5
      - cftime==1.6.5
      - charset-normalizer==3.4.4
      - distro==1.9.0
      - f90nml==1.5.0
      - filelock==3.20.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jax==0.8.0
      - jaxlib==0.8.0
      - jaxtyping==0.3.3
      - jinja2==3.1.6
      - jiter==0.11.1
      - markupsafe==3.0.3
      - ml-dtypes==0.5.3
      - monty==2025.3.3
      - mpmath==1.3.0
      - netcdf4==1.7.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.6.0
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyevtk==1.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2025.9.1
      - requests==2.32.5
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - simsopt==1.10.2
      - sniffio==1.3.1
      - sympy==1.14.0
      - torch==2.9.0
      - triton==3.5.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - vmecpp==0.4.9
      - wadler-lindig==0.1.7
prefix: /home/wenhao/miniconda3/envs/mollm_env
