exper_name: "constellaration problem 3"
description: "Multi-objective ideal-MHD stable QI stellarators"
save_dir: "./moo_results/fusion"
save_suffix: "1023"
resume: False

model:
  name: zgca,gemini-2.5-flash-nothinking
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 
use_au: False  # If True, this will use au model, set to false if you only want to use one LLM

goals: [l_delta_b,aspect_ratio]
optimization_direction: [max,min]
prompt_info_path: problem/fusion/prompt_info.yaml   
### Important ###
evalutor_path: problem.fusion.evaluator

optimization: 
  pop_size: 50
  eval_budget: 5000

early_stopping: False
inject_per_generation: 5




